const categories = [
  {
    slug: 'online-learning',
    name: 'Online learning',
    icon: 'bi-laptop',
    description: 'Courses, lectures, and structured learning paths.',
  },
  {
    slug: 'books',
    name: 'Books and notes',
    icon: 'bi-book',
    description: 'Books, open libraries, and study organization.',
  },
  {
    slug: 'institutional',
    name: 'Institutional learning',
    icon: 'bi-building',
    description: 'Tools used by schools, colleges, and private institutions.',
  },
  {
    slug: 'research',
    name: 'Research',
    icon: 'bi-search',
    description: 'Find papers, citations, and research communities.',
  },
  {
    slug: 'video',
    name: 'Video learning',
    icon: 'bi-play-btn',
    description: 'Visual lessons, explainers, and exam preparation.',
  },
  {
    slug: 'languages',
    name: 'Languages',
    icon: 'bi-translate',
    description: 'Build confidence in languages through daily practice.',
  },
  {
    slug: 'coding',
    name: 'Coding',
    icon: 'bi-code-slash',
    description: 'Practice programming and build technical skills.',
  },
  {
    slug: 'exams',
    name: 'Competitive exams',
    icon: 'bi-award',
    description: 'Preparation resources for academic and government exams.',
  },
  {
    slug: 'ai-tools',
    name: 'Educational AI',
    icon: 'bi-stars',
    description: 'Use AI tools thoughtfully for study, research, and creation.',
  },
];

const resources = [
  {
    name: 'Coursera',
    category: 'online-learning',
    access: 'Limited Free',
    url: 'https://www.coursera.org/',
    description:
      'University and industry courses across technology, business, and personal development.',
    bestFor: 'Structured courses',
    skills: 'courses certificates university learning',
    icon: 'Co',
    featured: true,
  },
  {
    name: 'edX',
    category: 'online-learning',
    access: 'Limited Free',
    url: 'https://www.edx.org/',
    description:
      'Courses from universities and institutions with audit options on many subjects.',
    bestFor: 'University learning',
    skills: 'courses university science technology',
    icon: 'ed',
    featured: true,
  },
  {
    name: 'Udemy',
    category: 'online-learning',
    access: 'Paid',
    url: 'https://www.udemy.com/',
    description:
      'A large marketplace of practical courses from independent instructors.',
    bestFor: 'Practical skills',
    skills: 'courses business coding design skills',
    icon: 'Ud',
    featured: false,
  },
  {
    name: 'Khan Academy',
    category: 'online-learning',
    access: 'Completely Free',
    url: 'https://www.khanacademy.org/',
    description:
      'Free lessons and practice for school subjects, math, science, and more.',
    bestFor: 'School fundamentals',
    skills: 'math science school practice sat',
    icon: 'KA',
    featured: true,
  },
  {
    name: 'SWAYAM',
    category: 'online-learning',
    access: 'Completely Free',
    url: 'https://swayam.gov.in/',
    description:
      'Indian government learning platform with courses from school to postgraduate level.',
    bestFor: 'Indian curriculum',
    skills: 'india courses college school nptel',
    icon: 'SW',
    featured: true,
  },
  {
    name: 'NPTEL',
    category: 'online-learning',
    access: 'Completely Free',
    url: 'https://nptel.ac.in/',
    description:
      'Engineering and science courses from Indian institutes and faculty.',
    bestFor: 'Engineering depth',
    skills: 'engineering technology iit science courses',
    icon: 'NP',
    featured: true,
  },
  {
    name: 'Google Books',
    category: 'books',
    access: 'Free + Paid',
    url: 'https://books.google.com/',
    description: 'Search and preview books, textbooks, and reference material.',
    bestFor: 'Book discovery',
    skills: 'books textbooks reference reading',
    icon: 'GB',
  },
  {
    name: 'Project Gutenberg',
    category: 'books',
    access: 'Completely Free',
    url: 'https://www.gutenberg.org/',
    description:
      'A large collection of public-domain ebooks for reading and reference.',
    bestFor: 'Classic literature',
    skills: 'books literature ebooks reading',
    icon: 'PG',
  },
  {
    name: 'Open Library',
    category: 'books',
    access: 'Completely Free',
    url: 'https://openlibrary.org/',
    description:
      'An open, searchable catalog with digital lending for many books.',
    bestFor: 'Library access',
    skills: 'books library research reading',
    icon: 'OL',
  },
  {
    name: 'Internet Archive',
    category: 'books',
    access: 'Completely Free',
    url: 'https://archive.org/',
    description:
      'A nonprofit digital library of books, media, software, and archived pages.',
    bestFor: 'Open archives',
    skills: 'books archive research history media',
    icon: 'IA',
  },
  {
    name: 'Notion',
    category: 'books',
    access: 'Limited Free',
    url: 'https://www.notion.so/',
    description:
      'Flexible notes, study planning, databases, and personal knowledge organization.',
    bestFor: 'Study organization',
    skills: 'notes planning productivity knowledge study',
    icon: 'No',
  },
  {
    name: 'Google Classroom',
    category: 'institutional',
    access: 'Completely Free',
    url: 'https://classroom.google.com/',
    description:
      'A classroom workflow for assignments, announcements, and feedback.',
    bestFor: 'School coordination',
    skills: 'school college assignments classroom institution',
    icon: 'GC',
    featured: true,
  },
  {
    name: 'Microsoft Teams',
    category: 'institutional',
    access: 'Limited Free',
    url: 'https://www.microsoft.com/microsoft-teams/',
    description:
      'Communication, meetings, files, and class collaboration for institutions.',
    bestFor: 'Class collaboration',
    skills: 'school college meetings institution private',
    icon: 'MT',
  },
  {
    name: 'Moodle',
    category: 'institutional',
    access: 'Completely Free',
    url: 'https://moodle.org/',
    description:
      'Open-source learning management software for schools and organizations.',
    bestFor: 'Open LMS',
    skills: 'lms school college open source institution',
    icon: 'Mo',
    featured: true,
  },
  {
    name: 'Canvas LMS',
    category: 'institutional',
    access: 'Limited Free',
    url: 'https://www.instructure.com/canvas',
    description:
      'Learning management tools used by schools, colleges, and training teams.',
    bestFor: 'College courses',
    skills: 'lms college courses institution private',
    icon: 'Ca',
  },
  {
    name: 'Blackboard',
    category: 'institutional',
    access: 'Paid',
    url: 'https://www.blackboard.com/',
    description:
      'Enterprise learning tools for educational institutions and instructors.',
    bestFor: 'Institutional learning',
    skills: 'lms college university institution private',
    icon: 'Bb',
  },
  {
    name: 'Google Scholar',
    category: 'research',
    access: 'Completely Free',
    url: 'https://scholar.google.com/',
    description:
      'Search scholarly literature, citations, theses, and research papers.',
    bestFor: 'Paper discovery',
    skills: 'research papers citations scholar thesis',
    icon: 'GS',
    featured: true,
  },
  {
    name: 'Semantic Scholar',
    category: 'research',
    access: 'Completely Free',
    url: 'https://www.semanticscholar.org/',
    description:
      'AI-assisted discovery of academic papers and related research.',
    bestFor: 'Research discovery',
    skills: 'research papers ai citations science',
    icon: 'SS',
  },
  {
    name: 'JSTOR',
    category: 'research',
    access: 'Limited Free',
    url: 'https://www.jstor.org/',
    description:
      'Academic journals, books, and primary sources with free and institutional access.',
    bestFor: 'Academic reading',
    skills: 'research journals humanities college',
    icon: 'JS',
  },
  {
    name: 'ResearchGate',
    category: 'research',
    access: 'Limited Free',
    url: 'https://www.researchgate.net/',
    description:
      'A network for researchers to share work and discuss academic topics.',
    bestFor: 'Research community',
    skills: 'research papers network science academics',
    icon: 'RG',
  },
  {
    name: 'IEEE Xplore',
    category: 'research',
    access: 'Paid',
    url: 'https://ieeexplore.ieee.org/',
    description:
      'Technical papers, standards, and conference content in engineering and computing.',
    bestFor: 'Engineering research',
    skills: 'research engineering ieee technology papers',
    icon: 'IE',
  },
  {
    name: 'YouTube',
    category: 'video',
    access: 'Completely Free',
    url: 'https://www.youtube.com/',
    description:
      'A broad video library with lectures, tutorials, and subject explainers.',
    bestFor: 'Visual explainers',
    skills: 'video lectures tutorials learning subjects',
    icon: 'YT',
    featured: true,
  },
  {
    name: 'TED-Ed',
    category: 'video',
    access: 'Completely Free',
    url: 'https://ed.ted.com/',
    description:
      'Short animated lessons and questions designed to spark curiosity.',
    bestFor: 'Curiosity learning',
    skills: 'video lessons school science ideas',
    icon: 'TE',
  },
  {
    name: 'Physics Wallah',
    category: 'video',
    access: 'Limited Free',
    url: 'https://www.pw.live/',
    description:
      'Exam preparation and learning content with a strong focus on Indian students.',
    bestFor: 'Exam preparation',
    skills: 'video jee neet exams india physics',
    icon: 'PW',
  },
  {
    name: "BYJU'S",
    category: 'video',
    access: 'Paid',
    url: 'https://byjus.com/',
    description:
      'Digital learning programs and exam preparation for school students.',
    bestFor: 'School programs',
    skills: 'video school exams jee neet india',
    icon: 'BY',
  },
  {
    name: 'Unacademy',
    category: 'video',
    access: 'Limited Free',
    url: 'https://unacademy.com/',
    description:
      'Live and recorded classes for exams, academics, and professional learning.',
    bestFor: 'Exam classes',
    skills: 'video exams upsc jee neet banking india',
    icon: 'UN',
  },
  {
    name: 'Duolingo',
    category: 'languages',
    access: 'Limited Free',
    url: 'https://www.duolingo.com/',
    description: 'Short, gamified lessons for building a daily language habit.',
    bestFor: 'Daily practice',
    skills: 'language english hindi speaking vocabulary',
    icon: 'Du',
    featured: true,
  },
  {
    name: 'Memrise',
    category: 'languages',
    access: 'Limited Free',
    url: 'https://www.memrise.com/',
    description: 'Language practice built around useful phrases and listening.',
    bestFor: 'Conversation practice',
    skills: 'language vocabulary speaking listening',
    icon: 'Me',
  },
  {
    name: 'Busuu',
    category: 'languages',
    access: 'Limited Free',
    url: 'https://www.busuu.com/',
    description:
      'Language courses with structured lessons and practice activities.',
    bestFor: 'Structured language study',
    skills: 'language courses speaking grammar',
    icon: 'Bu',
  },
  {
    name: 'BBC Learning English',
    category: 'languages',
    access: 'Completely Free',
    url: 'https://www.bbc.co.uk/learningenglish',
    description:
      'Free English lessons, vocabulary, pronunciation, and current-language practice.',
    bestFor: 'English confidence',
    skills: 'language english grammar pronunciation listening',
    icon: 'BBC',
    featured: true,
  },
  {
    name: 'LeetCode',
    category: 'coding',
    access: 'Limited Free',
    url: 'https://leetcode.com/',
    description:
      'Programming problems and interview preparation across many topics.',
    bestFor: 'Interview practice',
    skills: 'coding python java algorithms interview dsa',
    icon: 'LC',
    featured: true,
  },
  {
    name: 'freeCodeCamp',
    category: 'coding',
    access: 'Completely Free',
    url: 'https://www.freecodecamp.org/',
    description:
      'Free coding curriculum with projects in web development, data, and more.',
    bestFor: 'Beginner coding',
    skills: 'coding javascript python web projects',
    icon: 'fC',
    featured: true,
  },
  {
    name: 'GeeksforGeeks',
    category: 'coding',
    access: 'Limited Free',
    url: 'https://www.geeksforgeeks.org/',
    description:
      'Programming explanations, algorithms, interview preparation, and practice.',
    bestFor: 'Technical revision',
    skills: 'coding algorithms dsa python java interview',
    icon: 'GF',
  },
  {
    name: 'HackerRank',
    category: 'coding',
    access: 'Limited Free',
    url: 'https://www.hackerrank.com/',
    description:
      'Skill-based coding challenges and assessments for learners and candidates.',
    bestFor: 'Coding practice',
    skills: 'coding python sql java challenges interview',
    icon: 'HR',
  },
  {
    name: 'Testbook',
    category: 'exams',
    access: 'Limited Free',
    url: 'https://testbook.com/',
    description:
      'Practice tests and preparation resources for government and competitive exams.',
    bestFor: 'Government exams',
    skills: 'exams ssc banking gate upsc government india',
    icon: 'TB',
    featured: true,
  },
  {
    name: 'Adda247',
    category: 'exams',
    access: 'Limited Free',
    url: 'https://www.adda247.com/',
    description:
      'Exam classes, quizzes, and preparation resources for Indian competitive exams.',
    bestFor: 'Banking and SSC',
    skills: 'exams ssc banking upsc government india',
    icon: 'A7',
  },
  {
    name: 'ChatGPT',
    category: 'ai-tools',
    access: 'Limited Free',
    url: 'https://chatgpt.com/',
    description:
      'Ask for explanations, examples, study plans, and practice questions while checking the output.',
    bestFor: 'Explanations and brainstorming',
    skills: 'ai study writing coding explanations chatbot',
    icon: 'CG',
    featured: true,
    ai: true,
  },
  {
    name: 'Google Gemini',
    category: 'ai-tools',
    access: 'Limited Free',
    url: 'https://gemini.google.com/',
    description:
      'A general AI assistant for learning, research, and multimodal tasks.',
    bestFor: 'Research and multimodal work',
    skills: 'ai study research google chatbot',
    icon: 'Ge',
    ai: true,
  },
  {
    name: 'Claude',
    category: 'ai-tools',
    access: 'Limited Free',
    url: 'https://claude.ai/',
    description:
      'Long-form reasoning, writing support, and document analysis for study work.',
    bestFor: 'Writing and documents',
    skills: 'ai writing reasoning documents chatbot',
    icon: 'Cl',
    ai: true,
  },
  {
    name: 'Perplexity AI',
    category: 'ai-tools',
    access: 'Limited Free',
    url: 'https://www.perplexity.ai/',
    description:
      'Research-oriented answers with web sources that should still be verified.',
    bestFor: 'Research starting points',
    skills: 'ai research sources search chatbot',
    icon: 'Pe',
    ai: true,
  },
  {
    name: 'Microsoft Copilot',
    category: 'ai-tools',
    access: 'Limited Free',
    url: 'https://copilot.microsoft.com/',
    description:
      'AI assistance for learning, productivity, and Microsoft ecosystem tasks.',
    bestFor: 'Productivity and coding',
    skills: 'ai coding microsoft productivity chatbot',
    icon: 'MC',
    ai: true,
  },
  {
    name: 'NotebookLM',
    category: 'ai-tools',
    access: 'Limited Free',
    url: 'https://notebooklm.google.com/',
    description:
      'Ask questions about your own source material and build study notes from it.',
    bestFor: 'Source-based study',
    skills: 'ai notes research documents study',
    icon: 'NL',
    ai: true,
  },
  {
    name: 'Wolfram Alpha',
    category: 'ai-tools',
    access: 'Limited Free',
    url: 'https://www.wolframalpha.com/',
    description:
      'Computational answers and step-by-step support for mathematics and science.',
    bestFor: 'Math and science',
    skills: 'ai math science calculations education',
    icon: 'WA',
    ai: true,
  },
  {
    name: 'GitHub Copilot',
    category: 'ai-tools',
    access: 'Paid',
    url: 'https://github.com/features/copilot',
    description:
      'AI coding assistance for developers learning and building software.',
    bestFor: 'Coding support',
    skills: 'ai coding programming github developer',
    icon: 'GH',
    ai: true,
  },
  {
    name: 'Gamma',
    category: 'ai-tools',
    access: 'Limited Free',
    url: 'https://gamma.app/',
    description: 'Create presentations and visual documents from an outline.',
    bestFor: 'Presentation drafts',
    skills: 'ai presentations design writing students',
    icon: 'Ga',
    ai: true,
  },
  {
    name: 'Quizlet',
    category: 'ai-tools',
    access: 'Limited Free',
    url: 'https://quizlet.com/',
    description:
      'Flashcards, practice tests, and study activities for recall practice.',
    bestFor: 'Revision and recall',
    skills: 'ai flashcards quizzes study exams',
    icon: 'Qu',
    ai: true,
  },
  {
    name: 'Grammarly',
    category: 'ai-tools',
    access: 'Limited Free',
    url: 'https://www.grammarly.com/',
    description: 'Writing feedback for clarity, grammar, and tone.',
    bestFor: 'Writing improvement',
    skills: 'ai writing grammar english students',
    icon: 'Gr',
    ai: true,
  },
  {
    name: 'Khanmigo',
    category: 'ai-tools',
    access: 'Paid',
    url: 'https://www.khanmigo.ai/',
    description:
      'Khan Academy’s AI learning companion with guided tutoring experiences.',
    bestFor: 'Guided tutoring',
    skills: 'ai tutoring math school khan',
    icon: 'Km',
    ai: true,
  },
  {
    name: 'Elicit',
    category: 'ai-tools',
    access: 'Limited Free',
    url: 'https://elicit.com/',
    description:
      'Research assistant for finding and synthesizing academic papers.',
    bestFor: 'Literature reviews',
    skills: 'ai research papers literature review',
    icon: 'El',
    ai: true,
  },
  {
    name: 'Consensus',
    category: 'ai-tools',
    access: 'Limited Free',
    url: 'https://consensus.app/',
    description:
      'Search academic research and explore evidence-oriented summaries.',
    bestFor: 'Evidence discovery',
    skills: 'ai research academic papers evidence',
    icon: 'Co',
    ai: true,
  },
];

function getCategories() {
  return categories;
}

function getResources() {
  return resources;
}

function getFeaturedResources() {
  return resources.filter((resource) => resource.featured).slice(0, 8);
}

function getCategoryCounts() {
  return categories.map((category) => ({
    ...category,
    count: resources.filter((resource) => resource.category === category.slug)
      .length,
  }));
}

module.exports = {
  getCategories,
  getResources,
  getFeaturedResources,
  getCategoryCounts,
};
